#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-base
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-base"
BORRAR_DIVERTS_21= "/etc/issue /etc/bash.bashrc /etc/issue.net /etc/skel/.bashrc /etc/skel/.mozilla/firefox/canaima.default/places.sqlite /etc/skel/.mozilla/firefox/canaima.default/cert8.db /etc/skel/.mozilla/firefox/canaima.default/prefs.js /etc/skel/.mozilla/firefox/profiles.ini /var/run/motd"
BORRAR_LENGUAJES="af am an ang ar ara as ast az az_IR bal be be@latin bem bg bn bn_IN br bs byn ca ca@valencia ckb co crh cs csb currency cy da de de_AT dv dz el en_AU en@boldquot en_CA en_GB en_NZ en@quot en@shaw en_US@piglatin eo es_CL es_CO es_CR es_DO es_EC es_GT es_HN es_MX es_NI es_PA es_PE es_PR es_SV es_UY et et_EE eu fa fi fil fo fr frp fur fy ga gez gl gn gu gv ha haw he he_IL hi hr hu hy ia id ig io is it it_IT ja jv ka kk km kn ko kok ks ku ky l10n la lb lg li lo lt lv mai mg mi mk ml mn mr ms ms_MY mt my my_MM nb nb_NO nds ne nl nn no nso oc or pa pl ps  pt_PT qu rm ro ru ru_RU rw sc si sk sl so sq sr sr@ije sr@latin sr@Latn sv sw ta te tet tg th ti tig tk tl tr tr_TR tt ug uk uk_UA ur urd ur_PK uz uz@cyrillic ve vi wa wal wo xh yi yo zh zh_CN zh_HK zh_TW zu"
# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

function ERROR() {
echo -e ${ROJO}${1}${FIN}
exit 1
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}

case ${1} in

	configure)

	ADVERTENCIA "Removiendo diverts obsoletos de Canaima 2.1"
	for archivo in ${BORRAR_DIVERTS_21}; do
		BASE=$(basename ${archivo})
		dpkg-divert --package ${PKG} --remove --divert /var/lib/${PKG}/diverts/${BASE} ${archivo}
	done

	ADVERTENCIA "Regenerando los locales para es_VE.UTF-8"
	echo 'LANG="es_VE.UTF-8"' > /etc/default/locale
	echo 'LANGUAGE="es_VE:es"' >> /etc/default/locale
	echo 'LC_ALL="es_VE.UTF-8"' >> /etc/default/locale
	echo 'es_VE.UTF-8 UTF-8' > /etc/locale.gen
	export LC_ALL="es_VE.UTF-8"
	export LANGUAGE="es_VE:es"
	export LANG="es_VE.UTF-8"

	if [ -x $( which locale-gen ) ]; then
		locale-gen
	fi

	for lenguaje in ${BORRAR_LENGUAJES}; do
		rm -rf /usr/share/locale/${lenguaje}
	done

	ADVERTENCIA "Estableciendo modelo de teclado latam, pc105"	
	sed -i "s/$( grep 'XKBMODEL' /etc/default/keyboard )/XKBMODEL='pc105'/g" /etc/default/keyboard
	sed -i "s/$( grep 'XKBLAYOUT' /etc/default/keyboard )/XKBLAYOUT='latam'/g" /etc/default/keyboard

	ADVERTENCIA "Respaldando /etc/apt/sources.list en /etc/apt/sources.list.respaldo"
	[ -e /etc/apt/sources.list ] && mv /etc/apt/sources.list /etc/apt/sources.list.respaldo
	ADVERTENCIA "Respaldando /etc/apt/preferences en /etc/apt/preferences.respaldo"
	[ -e /etc/apt/preferences ] && mv /etc/apt/preferences /etc/apt/preferences.respaldo
	ADVERTENCIA "Respaldando /etc/locale.nopurge en /etc/locale.nopurge.respaldo"
	[ -e /etc/locale.nopurge ] && mv /etc/locale.nopurge /etc/locale.nopurge.respaldo

	ADVERTENCIA "Borrando repositorios ocultos en /etc/apt/sources.list.d/"
	rm -rf /etc/apt/sources.list.d/*

ADVERTENCIA "Escribiendo nuevos valores en /etc/apt/sources.list"
cat <<EOF >/etc/apt/sources.list
#
# Repositorios de Canaima GNU/Linux
#

# Repositorio Estable
#deb http://repositorio.canaima.softwarelibre.gob.ve/ estable usuarios

# Repositorio de Pruebas
deb http://repositorio.canaima.softwarelibre.gob.ve/ pruebas usuarios

# Repositorio de Desarrollo
#deb http://repositorio.canaima.softwarelibre.gob.ve/ desarrollo usuarios

# Repositorio de la Base (Debian)
deb http://universo.canaima.softwarelibre.gob.ve/ squeeze main contrib non-free

# Repositorio de actualizaciones de Emergencia
deb http://seguridad.canaima.softwarelibre.gob.ve/ seguridad usuarios

EOF

ADVERTENCIA "Escribiendo nuevos valores en /etc/apt/preferences"
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Canaima
Pin-Priority: 900

Package: *
Pin: release o=Debian
Pin-Priority: 100

EOF

ADVERTENCIA "Escribiendo nuevos valores en /etc/locale.nopurge"
cat <<EOF >/etc/locale.nopurge
####################################################
# This is the configuration file for localepurge(8).
####################################################

####################################################
# Uncommenting this string enables removal of localized
# man pages based on the configuration information for
# locale files defined below:

MANDELETE

####################################################
# Uncommenting this string causes localepurge to simply delete
# locales which have newly appeared on the system without
# bothering you about it:

DONTBOTHERNEWLOCALE

####################################################
# Uncommenting this string enables display of freed disk
# space if localepurge has purged any superfluous data:

#SHOWFREEDSPACE

#####################################################
# Commenting out this string enables faster but less
# accurate calculation of freed disk space:

QUICKNDIRTYCALC

#####################################################
# Commenting out this string disables verbose output:

#VERBOSE

#####################################################
# Following locales won't be deleted from this system
# after package installations done with apt-get(8):

es
es_ES.UTF-8
es_VE
es_VE.UTF-8

EOF

	ADVERTENCIA "Reconfigurando localepurge"
	export DEBIAN_FRONTEND="noninteractive"
	dpkg-reconfigure -fnoninteractive localepurge

	#----- Inicio del parche de Lennart Poettering ---------------------------------------------------------------#
	#=============================================================================================================#
	ADVERTENCIA "Parcheando el sistema con el script de Lennart Poettering"

	# Para cada usuario en /home/ ...
	for usuario in /home/*? ; do

		# Obtenemos sólo el nombre del usuario
		usuario_min=$(basename ${usuario})

		# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
		case $(grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow) in

			'')
			# No hace nada si no se encuentra en /etc/shadow
			;;

			*)

			# Especificamos cuál es el archivo .bashrc
			BASHRC_F="/home/${usuario_min}/.bashrc"

			# Si la línea "/sys/fs/cgroup/cpu/user" no se encuentra en el archivo .bashrc,
			# quiere decir que el script no ha sido implementado en éste sistema
			if [ $( cat ${BASHRC_F} | grep "/sys/fs/cgroup/cpu/user" | wc -l ) == "0" ]; then

				# Respaldamos el archivo .bashrc anterior en .bashrc.respaldo
				echo "Respaldando ${BASHRC_F} en ${BASHRC_F}.respaldo"
				[ ! -e ${BASHRC_F}.respaldo ] && cp ${BASHRC_F} ${BASHRC_F}.respaldo

				echo "Parcheando ${BASHRC_F}"

				# Éste bloque de código se agrega al archivo .bashrc y es parte de lo propuesto por 
				# Lennart Poettering.
				echo "if [ \"\$PS1\" ] ; then" >> ${BASHRC_F}
				echo "mkdir -p -m 0700 /sys/fs/cgroup/cpu/user/\$\$ > /sys/fs/null 2>&1" >> ${BASHRC_F}
				echo "echo \$\$ > /sys/fs/cgroup/cpu/user/\$\$/tasks" >> ${BASHRC_F}
				echo "echo \"1\" > /sys/fs/cgroup/cpu/user/\$\$/notify_on_release" >> ${BASHRC_F}
				echo "fi" >> ${BASHRC_F}

				chown ${usuario_min}:${usuario_min} ${BASHRC_F}

			else

				# Si la línea "/sys/fs/cgroup/cpu/user" se encuentra presente en el archivo
				# .bashrc quiere decir que ya se aplicó el script. Se ignora.
				ERROR "Parece que ya aplicaste el patch a ${BASHRC_F} con anterioridad. Ignorando."

			fi

			;;
		esac
	done

	# Especificando donde está el archivo rc.local
	RCLOCAL_F="/etc/rc.local"

	# Si la línea "/sys/fs/cgroup/cpu/release_agent" no se encuentra en el archivo rc.local,
	# quiere decir que el script no ha sido implementado en éste sistema
	if [ $( cat ${RCLOCAL_F} | grep "/sys/fs/cgroup/cpu/release_agent" | wc -l ) == "0" ]; then

		# Determinemos cuál es el número de línea del último comando "exit 0" dentro del archivo rc.local
		INSERTAR=$( cat ${RCLOCAL_F} | grep -n "exit 0" | sort -nr | head -n 1 | awk -F: '{print $1}' )

		# Respaldamos el archivo rc.local en rc.local.respaldo
		echo "Respaldando ${RCLOCAL_F} en ${RCLOCAL_F}.respaldo"
		[ ! -e ${RCLOCAL_F}.respaldo ] && cp ${RCLOCAL_F} ${RCLOCAL_F}.respaldo

		echo "Parcheando ${RCLOCAL_F}"

		# Insertamos éste bloque de código justo antes del último "exit 0" en un archivo temporal rc.local.nuevo
		sed "${INSERTAR}imkdir -p /sys/fs/cgroup/cpu\nmount -t cgroup cgroup /sys/fs/cgroup/cpu -o cpu\nmkdir -m 0777 /sys/fs/cgroup/cpu/user\necho \"/usr/local/sbin/cgroup_clean\" > /sys/fs/cgroup/cpu/release_agent" /etc/rc.local >> "${RCLOCAL_F}.nuevo"

		# Movemos el archivo temporal a su ubicación permanente
		mv ${RCLOCAL_F}.nuevo ${RCLOCAL_F}

		echo "Otorgando permisos de ejecución a ${RCLOCAL_F}"
		chmod +x ${RCLOCAL_F}

	else

		# Si la línea "/sys/fs/cgroup/cpu/release_agent" se encuentra presente en el archivo
		# rc.local quiere decir que ya se aplicó el script. Se ignora.
		ERROR "Parece que ya aplicaste el patch a ${RCLOCAL_F} con anterioridad. Ignorando."

	fi

	# Especificando donde está el archivo cgroup_clean
	CGROUP_F="/usr/local/sbin/cgroup_clean"

	echo "Creando ${CGROUP_F}"

	# Insertamos el siguiente bloque de código en cgroup_clean
	echo "#!/bin/sh" > ${CGROUP_F}
	echo "if [ \"\$*\" != \"/user\" ]; then" >> ${CGROUP_F}
	echo "rmdir /sys/fs/cgroup/cpu/\$*" >> ${CGROUP_F}
	echo "fi" >> ${CGROUP_F}

	echo "Otorgando permisos de ejecución a ${CGROUP_F}"
	chmod +x ${CGROUP_F}

	#----- Fin del parche de Lennart Poettering ------------------------------------------------------------------#
	#=============================================================================================================#

	ADVERTENCIA "Removiendo scripts de inicio usualmente innecesarios"

	for list in ${LIST}; do
		if [ -n ${LAPTOP} ]; then
			if [ ${list} != "bluetooth" ] || [ ${list} != "bluez-utils" ] || [ ${list} != "hibernate" ] || [ ${list} != "pcmciautils" ]; then
				update-rc.d -f ${list} remove
				rm -rf /etc/init.d/${list}
			fi
		else
			update-rc.d -f ${list} remove
			rm -rf /etc/init.d/${list}
		fi
	done

	if [ -e /etc/default/rcS ]; then
		ADVERTENCIA "Cambiando la forma de carga de las dependencias iniciales del sistema (CONCURRENCY=makefile)"
		[ -z $( grep "CONCURRENCY=makefile" /etc/default/rcS ) ] && echo 'CONCURRENCY=makefile' >> /etc/default/rcS
	fi

	if [ -e /etc/sysctl.conf ]; then
		ADVERTENCIA "Reduciendo la cantidad de procesos que se swapean, la RAM es más rápida (vm.swappiness)"
		[ -z $( grep "vm.swappiness=10" /etc/sysctl.conf ) ] && echo 'vm.swappiness=10' >> /etc/sysctl.conf
	fi

	if [ -e /etc/default/prelink ]; then
		ADVERTENCIA "Pre-enlazando librerías para mejorar la eficiencia de Canaima (prelink)"
		echo "Éste proceso tomará un poco de tiempo dependiendo de la cantidad de programas instalados ..."
		echo "Le recomendamos que se tome un buen café venezolano mientras espera."
		sed -i 's/PRELINKING=unknown/PRELINKING=yes/g' /etc/default/prelink
		sed -i 's/PRELINKING=no/PRELINKING=yes/g' /etc/default/prelink
		/etc/cron.daily/prelink
	fi

	if [ -e /etc/inittab ];	then
		ADVERTENCIA "Reduciendo cantidad de TTY'S a 2, el usuario no las usa todas en realidad"
		sed -i 's/3:23:respawn:\/sbin\/getty/#3:23:respawn:\/sbin\/getty/g' /etc/inittab
		sed -i 's/4:23:respawn:\/sbin\/getty/#4:23:respawn:\/sbin\/getty/g' /etc/inittab
		sed -i 's/5:23:respawn:\/sbin\/getty/#5:23:respawn:\/sbin\/getty/g' /etc/inittab
		sed -i 's/6:23:respawn:\/sbin\/getty/#6:23:respawn:\/sbin\/getty/g' /etc/inittab
	fi

	ADVERTENCIA "Añadiendo noatime a /etc/fstab"

	if [ $( cat ${FSTAB} | grep -c "Optimizado para Canaima GNU/Linux" ) == 0 ]; then
		echo "#" >> ${FSTAB}
		echo "# Optimizado para Canaima GNU/Linux (agregado noatime a las opciones de disco)" >> ${FSTAB}
		echo "#" >> ${FSTAB}
	fi

	sed -i 's/   / /g' ${FSTAB}
	sed -i 's/   / /g' ${FSTAB}
	sed -i 's/  / /g' ${FSTAB}
	sed -i 's/  / /g' ${FSTAB}
	sed -i 's/, /,/g' ${FSTAB}
	sed -i 's/  / /g' ${FSTAB}
	sed -i 's/  / /g' ${FSTAB}

	for datos in $( cat ${FSTAB} | awk '{print $3"##--TOKEN--##"$2"##--TOKEN--##"$4"##--TOKEN--##"$1}' ); do

		for fs in ext2 ext3 ext4 xfs ; do

		if [ $( echo $( expr "$datos" : "$fs" ) ) == 4 ]; then

		parsing=${datos#$fs##--TOKEN--##}
		dispositivo=$( echo $parsing | sed 's/##--TOKEN--##/ /g' | awk '{print $1}' )
		dispositivo=$( echo $dispositivo | sed 's/\//\\\//g' )
		propiedad=$( echo $parsing | sed 's/##--TOKEN--##/ /g' | awk '{print $2}' )
		uuid=$( echo $parsing | sed 's/##--TOKEN--##/ /g' | awk '{print $3}' )

		case ${propiedad} in

			"defaults")

			if [ $dispositivo == "\/" ]; then
				sed -i 's/'${uuid}' '${dispositivo}' '${fs}' '${propiedad}'/'${uuid}' '${dispositivo}' '${fs}' defaults,noatime,errors=remount-ro/g' ${FSTAB}
			else
				sed -i 's/'${uuid}' '${dispositivo}' '${fs}' '${propiedad}'/'${uuid}' '${dispositivo}' '${fs}' defaults,noatime/g' ${FSTAB}
			fi

			;;

			"errors=remount-ro,defaults")
				sed -i 's/'${uuid}' '${dispositivo}' '${fs}' '${propiedad}'/'${uuid}' '${dispositivo}' '${fs}' defaults,noatime,errors=remount-ro/g' ${FSTAB}
			;;

			"defaults,errors=remount-ro")
				sed -i 's/'${uuid}' '${dispositivo}' '${fs}' '${propiedad}'/'${uuid}' '${dispositivo}' '${fs}' defaults,noatime,errors=remount-ro/g' ${FSTAB}
			;;

			"errors=remount-ro")

			if [ $dispositivo == "\/" ]; then
				sed -i 's/'${uuid}' '${dispositivo}' '${fs}' '${propiedad}'/'${uuid}' '${dispositivo}' '${fs}' defaults,noatime,errors=remount-ro/g' ${FSTAB}
			else
				sed -i 's/'${uuid}' '${dispositivo}' '${fs}' '${propiedad}'/'${uuid}' '${dispositivo}' '${fs}' noatime,errors=remount-ro/g' ${FSTAB}
			fi

			;;

		esac

		fi

		done

	done

	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)

		echo "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1

	;;

esac

#DEBHELPER#

exit 0
