#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-base
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

ALTERNATIVES="/etc/apt/sources.list /etc/default/locale /etc/locale.gen /etc/default/keyboard"

case ${1} in
	configure|'')
		for ALT in ${ALTERNATIVES}; do
			ALTNAME="$( basename "${ALT}" )"

			if [ ! -e "/etc/canaima-base/alternatives/${ALTNAME}" ]; then
				mkdir -p "/etc/canaima-base/alternatives/"
				touch "/etc/canaima-base/alternatives/${ALTNAME}"
			fi

			if which ucf >/dev/null; then
				ucf -v "/usr/share/canaima-base/alternatives/${ALTNAME}" "/etc/canaima-base/alternatives/${ALTNAME}"
			fi

			if which ucfr >/dev/null; then
				ucfr -v canaima-base "/etc/canaima-base/alternatives/${ALTNAME}"
			fi

			ADVERTENCIA "Añadiendo alternativa para el archivo \"${ALT}\" ..."
			update-alternatives --force --install "${ALT}" "${ALTNAME}" "/etc/canaima-base/alternatives/${ALTNAME}" 60
		done

		if [ -x "$( which locale-gen )" ]; then
			ADVERTENCIA "Regenerando locales ..."
			locale-gen
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)

		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1

	;;

esac

#DEBHELPER#

exit 0
