#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-base
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-base"
# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

function ERROR() {
echo -e ${ROJO}${1}${FIN}
exit 1
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	ADVERTENCIA "Revirtiendo script de Lennart Poettering"

        # Para cada usuario en /home/ ...
        for usuario in /home/*? ; do

                # Obtenemos sólo el nombre del usuario
                usuario_min=$(basename ${usuario})

                # Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
                case $(grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow) in

                '')
                # No hace nada si no se encuentra en /etc/shadow
                ;;

                *)

	                BASHRC_F="/home/${usuario_min}/.bashrc"
			# Si existe un archivo de respaldo, lo restauramos
			[ -e ${BASHRC_F}.respaldo ] && mv ${BASHRC_F}.respaldo ${BASHRC_F}

			;;

		esac
	done

	RCLOCAL_F="/etc/rc.local"
	# Si existe un archivo de respaldo, lo restauramos
	[ -e ${RCLOCAL_F}.respaldo ] && mv ${RCLOCAL_F}.respaldo ${RCLOCAL_F}

	CGROUP_F="/usr/local/sbin/cgroup_clean"
	# Si existe el archivo /usr/local/sbin/cgroup_clean, lo borramos
	[ -e ${CGROUP_F} ] && rm -rf ${CGROUP_F}

	;;

	*)

		echo "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
