#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-base
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-base"

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	ADVERTENCIA "Restaurando antiguo /etc/default/locale"
	[ -e /etc/default/locale.respaldo ] && mv /etc/default/locale.respaldo /etc/default/locale
        
	ADVERTENCIA "Restaurando antiguo /etc/locale.gen"
	[ -e /etc/locale.gen.respaldo ] && mv /etc/locale.gen.respaldo /etc/locale.gen

	ADVERTENCIA "Restaurando antiguo /etc/default/keyboard"
	[ -e /etc/default/keyboard.respaldo ] && mv /etc/default/keyboard.respaldo /etc/default/keyboard

	ADVERTENCIA "Restaurando antiguo /etc/apt/sources.list"
	[ -e /etc/apt/sources.list.respaldo ] && mv /etc/apt/sources.list.respaldo /etc/apt/sources.list

	ADVERTENCIA "Restaurando antiguo /etc/apt/preferences"
	[ -e /etc/apt/preferences.respaldo ] && mv /etc/apt/preferences.respaldo /etc/apt/preferences

	;;

	*)

		echo "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0

