#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-base
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2010-2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
        printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
        printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
        printf "\033[1;32m${1}\033[0m\n"
}

ALTERNATIVES="/etc/apt/sources.list /etc/default/locale /etc/locale.gen /etc/default/keyboard"

case ${1} in
	remove|upgrade|deconfigure)
		for ALT in ${ALTERNATIVES}; do
			ALTNAME="$( basename "${ALT}" )"

			ADVERTENCIA "Removiendo alternativa para el archivo \"${ALT}\" ..."
			update-alternatives --remove "${ALTNAME}" "/etc/canaima-base/alternatives/${ALTNAME}"
		done

	;;

	failed-upgrade)
	;;

	*)

		echo "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac



exit 0
